services:
  api-txt:
    build: .
    container_name: gps-api-txt
    ports:
      - "9000:9000"
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped